services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USERNAME: ${MQTT_BACKEND_USERNAME}
      MQTT_PASSWORD: ${MQTT_BACKEND_PASSWORD}
      MQTT_TLS: ${MQTT_TLS:-}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      EMAIL_FROM: ${EMAIL_FROM:-IoT Dashboard <onboarding@resend.dev>}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_RECEIVER: ${EMAIL_RECEIVER}

  sensor:
    build:
      context: .
      dockerfile: sensors/Dockerfile
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USERNAME: ${MQTT_SENSOR_USERNAME}
      MQTT_PASSWORD: ${MQTT_SENSOR_PASSWORD}
      MQTT_TLS: ${MQTT_TLS:-}

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
