services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER: mqtt
      MQTT_PORT: "1883"
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_RECEIVER: ${EMAIL_RECEIVER}

  sensor:
    build:
      context: .
      dockerfile: sensors/Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
